### ISSUE TITLE
建议添加dleger集群模式支持

### ISSUE THREAD

**Issue by liuxin638507** [itboon/rocketmq-helm#1]
建议添加dleger集群模式支持，实现高可用选主

**Comment by itboon** [comment]
经过评估，dleger 优势是主节点宕机后能够自动进行故障转移，不足的地方是每组 broker 至少需要 3 个节点。
因为【多 Master 多 Slave 架构】具有高可用性，并且 k8s 具有自愈能力，所以 dleger 在 k8s 环境下性价比相当低，本项目不准备支持。
