### ISSUE TITLE
Error: Could not find or load main class org.apache.rocketmq.broker.BrokerStartup

### ISSUE THREAD

**Issue by HuangQAQ** [itboon/rocketmq-helm#10]
i use this charts deploy in my k8s , nameserver and master crash this bug:
Error: Could not find or load main class org.apache.rocketmq.broker.BrokerStartup
Error: Could not find or load main class org.apache.rocketmq.namesrv.NamesrvStartup

**Comment by itboon** [comment]
你是怎么部署的，请提供完整 helm install 命令，如果有 values 文件也请提供一下。

**Comment by zmoon460** [comment]
`# helm list`
`NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION`
`mq      default         1               2023-12-22 10:46:14.891059829 +0800 CST deployed        rocketmq-3.0.2  4.9.7  `

`[root@node01 app-deploy]# kubectl get pod `
`NAME                                     READY   STATUS    RESTARTS   AGE`
`mq-rocketmq-broker-master-0              1/1     Running   0          65m`
`mq-rocketmq-dashboard-58486c4fc7-k7j2l   1/1     Running   0          65m`
`mq-rocketmq-nameserver-0                 1/1     Running   0          65m`


my default install is fine

**Comment by HuangQAQ** [comment]
helm upgrade --install rocketmq \
  --namespace rocketmq-demo \
  --create-namespace \
  --set broker.size.master="3" \
  --set broker.size.replica="1" \
  --set broker.master.jvmMemory="-Xms2g -Xmx2g" \
  --set broker.master.resources.requests.memory="4Gi" \
  --set nameserver.replicaCount="3" \
  --set dashboard.enabled="true" \
  --set dashboard.ingress.enabled="true" \
  --set dashboard.ingress.hosts[0].host="rocketmq-ha.example.com" \
  rocketmq-repo/rocketmq

使用以上命令部署的，使用的是3节点的openshift集群

**Comment by HuangQAQ** [comment]
我在脚本中调试，发现没有/home/rocketmq/rocketmq-4.9.7这个目录

以下是日志：
openjdk version "1.8.0_372"
OpenJDK Runtime Environment (build 1.8.0_372-b07)
OpenJDK 64-Bit Server VM (build 25.372-b07, mixed mode)
+ java -server -XX:+UseG1GC -Xms1024M -Xmx1024M -cp '.:/home/rocketmq/rocketmq-4.9.7/conf:/home/rocketmq/rocketmq-4.9.7/lib/*:' org.apache.rocketmq.namesrv.NamesrvStartup
Error: Could not find or load main class org.apache.rocketmq.namesrv.NamesrvStartup
@itboon @zmoon460

**Comment by HuangQAQ** [comment]
I fixed this bug by editing openshift scc，Thanks！
