### ISSUE TITLE
JRE构建RocketMQ镜像的问题

### ISSUE THREAD

**Issue by zmoon460** [itboon/rocketmq-helm#11]
一直对rocketmq的官方启动脚本有点吐槽，其中除了产生一堆废弃java opt告警不说，最难受是判断JAVA_HOME的语句用了javac命令 ，容器里面就必须用JDK镜像，至少比JRE镜像大了100M以上，但不清楚 JRE_HOME替换JAVA_HOME 有哪些影响，一直没敢用JRE构建镜像

**Comment by itboon** [comment]
本项目将会兼容 JRE，启动脚本从 javac 切换到 java，项目保持与官方容器镜像兼容，第三方镜像需要用户自己把控。

**Comment by itboon** [comment]
7b5cb2555abc403b28032ab8637490dafa960375
