### ISSUE TITLE
测试部署代码中存在错误

### ISSUE THREAD

**Issue by wengych** [itboon/rocketmq-helm#14]
## 部署测试集群, 启用 Dashboard (默认已开启持久化存储)
helm upgrade --install rocketmq \
  --namespace rocketmq-demo \
  --create-namespace \
  --set dashboard.enabled="true" \CR_RELEASE_NAME_TEMPLATE="rocketmq-demo.example.com" \
  rocketmq-repo/rocketmq

\CR_RELEASE_NAME_TEMPLATE这部分是否不应该存在于helm upgrade命令中？

**Comment by itboon** [comment]
这里写错了，已经纠正，感谢反馈

## 部署案例

``` shell
## 部署一个最小化的 rocketmq 集群
## 这里关闭持久化存储，仅演示部署效果
helm upgrade --install rocketmq \
  --namespace rocketmq-demo \
  --create-namespace \
  --set broker.persistence.enabled="false" \
  rocketmq-repo/rocketmq
```

``` shell
## 部署测试集群, 启用 Dashboard (默认已开启持久化存储)
helm upgrade --install rocketmq \
  --namespace rocketmq-demo \
  --create-namespace \
  --set dashboard.enabled="true" \
  rocketmq-repo/rocketmq
```
