### ISSUE TITLE
部署后访问broker是内网ip

### ISSUE THREAD

**Issue by h956663978** [itboon/rocketmq-helm#2]
我按照安装说明部署后，访问namespace是内网ip，基于k8s提供网络。导致我的程序报错：connect to ******:10911 failed，我尝试在cm中修改broker暴露的ip地址，没有找到，能提供一下操作指南吗，谢谢

**Comment by itboon** [comment]
从 k8s 集群外访问 rocketmq 吗，当前不支持集群外暴露，有考虑在下个版本中完善。

**Comment by itboon** [comment]
@h956663978 可以详细介绍一下你的环境和需求，下个版本可考虑适配。

**Comment by xuyf1001** [comment]
您好，问一下，这个rocketmq集群的节点间的服务通信走的是ip还是域名？感觉像是ip啊

**Comment by itboon** [comment]
> 您好，问一下，这个rocketmq集群的节点间的服务通信走的是ip还是域名？感觉像是ip啊

@xuyf1001  client 通过域名访问 nameserver，nameserver 会返回 broker 的 ip，然后 client 通过 ip 访问 broker

**Comment by xuyf1001** [comment]
他上面讲的这个rocketmq,k8外部暴露使用，用nodeport是否可行？还要不要ingress增加解析域名等等呢？

**Comment by xuyf1001** [comment]
客户端通过nameserver返回的ip来访问broker是否会有ipv4和ipv6的兼容性问题呢？

**Comment by itboon** [comment]
> 他上面讲的这个rocketmq,k8外部暴露使用，用nodeport是否可行？还要不要ingress增加解析域名等等呢？

@xuyf1001 nodeport 可行但比较麻烦，需要修改 broker 配置项 `brokerIP1` （支持 ip 和域名）。麻烦的地方在于每个 broker 需要使用不同的 nodeport 端口号。 

broker 配置请参考: https://rocketmq.apache.org/zh/docs/4.x/bestPractice/01bestpractice#broker-%E9%85%8D%E7%BD%AE

**Comment by xuzheng0017** [comment]
5.x引入的proxy架构好像能解决你的问题
