### ISSUE TITLE
服务都起来了，RocketMQ仪表板里能发，用java不能发！

### ISSUE THREAD

**Issue by ilowe110** [itboon/rocketmq-helm#20]
![image](https://github.com/itboon/rocketmq-helm/assets/17997138/34d5dc03-37e6-4106-987a-099c1731af2c)
![image](https://github.com/itboon/rocketmq-helm/assets/17997138/916ad2ea-462f-4b54-9149-2e050f4e7509)

**Comment by itboon** [comment]
本项目不解决客户端SDK相关问题
