### ISSUE TITLE
请教下rocketmq的nameserver持久化

### ISSUE THREAD

**Issue by YuWan1117** [itboon/rocketmq-helm#3]
# nameserver持久化
1. 为什么nameserver需要持久化？如果不开启持久化会有什么影响？
2. nameserver持久化是存储哪些信息？

希望可以得到解答，感谢～🙏

**Comment by itboon** [comment]
nameserver 没有数据落盘，不需要持久化。
模板里面挂载了 /home/rocketmq/logs 目录，默认使用 emptyDir。如果 logs 数据过大可能会造成磁盘容量不足并引发 pod 被驱逐（驱逐后 emptyDir 会被清空），实际这个目录数据量很小，所以没有必要持久化。

**Comment by YuWan1117** [comment]
感谢解答，我理解也是nameserver无需持久化

在rocketmq-helm项目的examples/production.yaml路径下，我看prodction.yaml中开启了persistent所以产生疑问。

因此根据你的回答，生产是没必要开启persistent的。我们的github源码是否要同步变更～
