### ISSUE TITLE
建议dashboard增加NodePort暴露可选方式

### ISSUE THREAD

**Issue by liuxin638507** [itboon/rocketmq-helm#5]
对于快捷连接查看仪表盘，建议添加可选新增nodeport自定义端口暴露访问
values.yaml 变量新增
#########
  service:
#    type: ClusterIP
    type: NodePort
    nodePort: 30019
#########

templates/dashboard/service.yaml 修改为：

{{- if .Values.dashboard.enabled -}}
{{- $fullName := include "rocketmq.dashboard.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName| quote }}
{{- if eq .Values.dashboard.service.type "NodePort" }}
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: {{ .Values.dashboard.service.nodePort }}
{{- else }}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
{{- end }}
  selector:
    {{- include "rocketmq.selectorLabels" . | nindent 4 }}
    component: dashboard
{{- end }}

**Comment by itboon** [comment]
df6e222 已解决
`--set dashboard.service.type="NodePort"`
