### ISSUE TITLE
集群卸载后broker持久卷pvc挂载请教

### ISSUE THREAD

**Issue by liuxin638507** [itboon/rocketmq-helm#6]
集群卸载，原来的pvc也被卸载，由于卸载后pvc文件名变化，即使修改存储原来pvc跟之前对应，重新安装集群怎么确保master对应的原来master挂载路径、slaver对应挂载原来slave路径

**Comment by itboon** [comment]
这个问题超出了我的能力范围，以下提供一些思路：

1. 如果你用本项目 v2 版本部署了 rocketmq，卸载后 pvc 会保留，以同样的 release name 再次部署，pvc 会重新挂载，数据全部保留。
2. 如果你已被卸载的集群是用其他方式部署的，如果不在乎数据，你可以重新部署一套并挂载新的 pvc；如果需要保留原来的数据，建议按当初部署的方式复原试试。
3. 本项目 v2 与 v1 不兼容，不建议 v1 升级到 v2。
